version: '3.1'

services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    environment:
      - DOCKER=docker
    ports:
      - '80:4000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
